export interface PhytosanitaryAlert {
  id: string;
  provider: string;
  externalId?: string | null;
  cropId?: string | null;
  title: string;
  summary: string;
  province?: string | null;
  municipality?: string | null;
  severity?: string | null;
  publishedAt: string;
  sourceUrl?: string | null;
  sourceArticleUrl?: string | null;
  sourcePdfUrl?: string | null;
  sourceDocumentId?: string | null;
  sourceHash?: string | null;
  sourcePage?: number | null;
  sourcePublishedAt?: string | null;
  coverage?: string | null;
  region?: string | null;
  pestOrDisease?: string | null;
  recommendation?: string | null;
  validFrom?: string | null;
  validTo?: string | null;
  extractionVersion?: string | null;
  extractionStatus?: string | null;
  extractionConfidence?: number | null;
  evidenceText?: string | null;
  rawPayload?: Record<string, unknown> | null;
}
